Created Server by Node.js
mate-academy/node_case-transformer-server pull request #468
Opened 2023-10-12 07:55 UTC by olegpaunov

2023-10-13 15:24 UTC, BudnikOleksii requested changes
Good work 👍 
Left some comments. Check them and improve your solution

2023-10-13 15:24 UTC, BudnikOleksii commented on src/createServer.js
> +const supportedCases = ['SNAKE', 'KEBAB', 'CAMEL', 'PASCAL', 'UPPER'];
Move it to the constants file/folder

2023-10-13 15:24 UTC, BudnikOleksii commented on src/createServer.js
> +    }
- Let's create a helper that will check for errors.
- put all error messages into a constant
- Available cases are in the `supportedCases` constant, use them.
- avoid else statements

2023-10-13 15:24 UTC, BudnikOleksii commented on src/createServer.js
> +    if (errors.length === 0) {
```suggestion
    if (!errors.length) {
```

2023-10-13 15:24 UTC, BudnikOleksii commented on src/createServer.js
> +        convertedText: result.convertedText,
- originalText is convertedText? 🤯 
- `targetCase.toUpperCase()` you do it twice

2023-10-13 15:24 UTC, BudnikOleksii commented on src/createServer.js
> +    res.end(JSON.stringify(response.body));
Also, you need to add statusText:
- If something is not correct, you should respond with 400 status, Bad request statusText and the next payload
- You should respond with status 200 and OK status text.

2023-10-18 09:00 UTC, Moroz-Dmytro requested changes

2023-10-18 09:00 UTC, Moroz-Dmytro commented on src/createServer.js
> +    }
Move this logic to separate module

2023-10-18 09:00 UTC, Moroz-Dmytro commented on src/createServer.js
> +    const availableCases = 'Available cases: SNAKE, KEBAB, CAMEL, PASCAL, UPPER.';
Use your constant with available cases and `join` here

2023-10-18 09:00 UTC, Moroz-Dmytro commented on src/createServer.js
> +      body: errors.length > 0 ? { errors } : {},
```suggestion
      status: errors.length ? 400 : 200,
      statusText: errors.length ? 'Bad Request' : 'OK',
      headers: { 'Content-Type': 'application/json' },
      body: errors.length ? { errors } : {},
```

2023-10-18 09:00 UTC, Moroz-Dmytro commented on src/createServer.js
> +      };
```suggestion
      const { convertedText, originalCase } = convertToCase(convertedText, upperCaseTargetCase);

      response.body = {
        originalText: convertedText,
        targetCase: upperCaseTargetCase,
        convertedText,
        originalCase,
      };
```

2023-10-18 09:00 UTC, Moroz-Dmytro commented on src/createServer.js
> +    const convertedText = path.slice(1);
```suggestion
    const originalText = path.slice(1);
```

2023-10-20 07:36 UTC, Moroz-Dmytro requested changes

2023-10-20 07:36 UTC, Moroz-Dmytro commented on src/createServer.js
> +    const targetCase = query.get('toCase');
```suggestion
    const originalText = parsedUrl.pathname.slice(1);
    const targetCase = parsedUrl.searchParams.get('toCase');
```

2023-10-20 07:36 UTC, Moroz-Dmytro commented on src/createServer.js
> +      };
```suggestion
      const { convertedText, originalCase } = convertToCase(originalText, upperCaseTargetCase);

      response.body = {
        originalText,
        targetCase: upperCaseTargetCase,
        convertedText,
        originalCase,
      };
```

2023-10-20 07:36 UTC, Moroz-Dmytro commented on src/createServer.js
> +      const upperCaseTargetCase = targetCase.toUpperCase();
Why need to do this? It's not needed

2023-10-20 07:36 UTC, Moroz-Dmytro commented on src/requestValidation.js
> +  const availableCases = `Available cases: ${supportedCases.join(', ')}.`;
Move this to constants file and name them in UPPER_CASE

2023-10-20 07:36 UTC, Moroz-Dmytro commented on src/requestValidation.js
> +    const upperCaseTargetCase = targetCase.toUpperCase();
I guess we don't need to do this

2023-10-20 07:57 UTC, olegpaunov commented on src/createServer.js
> +      const upperCaseTargetCase = targetCase.toUpperCase();
Do you mean about the variable?

2023-10-20 08:02 UTC, olegpaunov commented on src/createServer.js
> +      const upperCaseTargetCase = targetCase.toUpperCase();
why do we need condition ? or variable?

2023-10-20 08:44 UTC, Moroz-Dmytro approved these changes

2023-10-20 08:44 UTC, Moroz-Dmytro commented on src/constants.js
> +const availableCases = `Available cases: ${supportedCases.join(', ')}.`;
All these constants should be named in UPPER_CASE

2024-03-20 11:23 UTC, closed without merging